{
  "formatVersion": "1.1",
  "component": {
    "group": "org.multipaz",
    "module": "multipaz",
    "version": "0.96.1-pre.2.ef0c0b51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "multipaz-metadata-0.96.1-pre.2.ef0c0b51.jar",
          "url": "multipaz-0.96.1-pre.2.ef0c0b51.jar",
          "size": 401321,
          "sha512": "4281186e7da1b85d451640332e80725acade15f3bac4fe815b7d07d6872ca7e27b640e8f38f0e251ad9ec5d66fdb6bb518c70bdc635b217dc72ece5909d34dba",
          "sha256": "d0a6e27f5af4b54d4988e84b020358c707b9728575eb16e9ed1182115ddf2798",
          "sha1": "280c7f8a033f1d34d6daf8b7dcfdb4e0035f7406",
          "md5": "a758c360a3ff000587b8fc39867ba5a6"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "multipaz-kotlin-0.96.1-pre.2.ef0c0b51-sources.jar",
          "url": "multipaz-0.96.1-pre.2.ef0c0b51-sources.jar",
          "size": 697407,
          "sha512": "61a28e48f9e41c63c5cd81242afaeb34ec673488c61457f583b7ad8d46cfad88970d49362a077ae80d2cfcfd5a88be4dec63f1289db3ded02abe27b6a0397aec",
          "sha256": "a7fdd36838c0391780599f722b9ddcd3c8f8048bb9b8c4a201d0333036dff2d7",
          "sha1": "2522f3fe6aa7c784fc79717ca333da9070f656b3",
          "md5": "70647555942d675e026bde6663d6ba10"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../multipaz-android/0.96.1-pre.2.ef0c0b51/multipaz-android-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-android",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../multipaz-android/0.96.1-pre.2.ef0c0b51/multipaz-android-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-android",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../multipaz-android/0.96.1-pre.2.ef0c0b51/multipaz-android-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-android",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-iosarm64/0.96.1-pre.2.ef0c0b51/multipaz-iosarm64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-iosarm64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-iosarm64/0.96.1-pre.2.ef0c0b51/multipaz-iosarm64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-iosarm64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-iosarm64/0.96.1-pre.2.ef0c0b51/multipaz-iosarm64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-iosarm64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-iossimulatorarm64/0.96.1-pre.2.ef0c0b51/multipaz-iossimulatorarm64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-iossimulatorarm64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-iossimulatorarm64/0.96.1-pre.2.ef0c0b51/multipaz-iossimulatorarm64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-iossimulatorarm64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-iossimulatorarm64/0.96.1-pre.2.ef0c0b51/multipaz-iossimulatorarm64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-iossimulatorarm64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-iosx64/0.96.1-pre.2.ef0c0b51/multipaz-iosx64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-iosx64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-iosx64/0.96.1-pre.2.ef0c0b51/multipaz-iosx64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-iosx64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-iosx64/0.96.1-pre.2.ef0c0b51/multipaz-iosx64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-iosx64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../multipaz-jvm/0.96.1-pre.2.ef0c0b51/multipaz-jvm-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-jvm",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../multipaz-jvm/0.96.1-pre.2.ef0c0b51/multipaz-jvm-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-jvm",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../multipaz-jvm/0.96.1-pre.2.ef0c0b51/multipaz-jvm-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-jvm",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    }
  ]
}
