{
  "formatVersion": "1.1",
  "component": {
    "group": "org.multipaz",
    "module": "multipaz-doctypes",
    "version": "0.96.1-pre.2.ef0c0b51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.multipaz",
          "module": "multipaz",
          "version": {
            "requires": "0.96.1-pre.2.ef0c0b51"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "multipaz-doctypes-metadata-0.96.1-pre.2.ef0c0b51.jar",
          "url": "multipaz-doctypes-0.96.1-pre.2.ef0c0b51.jar",
          "size": 20957,
          "sha512": "7c87dc4714e88329d0db87fd373319aa4ffe14091f690aa1850b03a5a4970ff78a26ef0b7fcaa79cf2df7b6098f35314bd49d758772b4f116ecced2a5b8923f3",
          "sha256": "cf00971507241510163b34396cc5c3676a821248534d430b45527a6f42db0252",
          "sha1": "39c49d7c6ca46f7643c93b13305affd82c12819a",
          "md5": "d2b34b7647bcc0e8e639b75d9c12f48a"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "multipaz-doctypes-kotlin-0.96.1-pre.2.ef0c0b51-sources.jar",
          "url": "multipaz-doctypes-0.96.1-pre.2.ef0c0b51-sources.jar",
          "size": 43068,
          "sha512": "bee4c72e30c13a106cc0be85c5e24746bf454a555e53f5bda7b37a4780b9ca3d4f143c06f82baca27cde86856f0853f29f0ef6b0107f5feba73a0c0d460d025e",
          "sha256": "3bc212df7356d4dcf55f1521727dd9bb9b7c03ba33cfe1023ba4cd0467468c0a",
          "sha1": "d93af0296d7d7b3c473cc9493831c3ef79bc1753",
          "md5": "5f75aae9397a9283dc00263aa526d4fd"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-doctypes-iosarm64/0.96.1-pre.2.ef0c0b51/multipaz-doctypes-iosarm64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-doctypes-iosarm64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-doctypes-iosarm64/0.96.1-pre.2.ef0c0b51/multipaz-doctypes-iosarm64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-doctypes-iosarm64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-doctypes-iosarm64/0.96.1-pre.2.ef0c0b51/multipaz-doctypes-iosarm64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-doctypes-iosarm64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-doctypes-iossimulatorarm64/0.96.1-pre.2.ef0c0b51/multipaz-doctypes-iossimulatorarm64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-doctypes-iossimulatorarm64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-doctypes-iossimulatorarm64/0.96.1-pre.2.ef0c0b51/multipaz-doctypes-iossimulatorarm64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-doctypes-iossimulatorarm64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-doctypes-iossimulatorarm64/0.96.1-pre.2.ef0c0b51/multipaz-doctypes-iossimulatorarm64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-doctypes-iossimulatorarm64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-doctypes-iosx64/0.96.1-pre.2.ef0c0b51/multipaz-doctypes-iosx64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-doctypes-iosx64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-doctypes-iosx64/0.96.1-pre.2.ef0c0b51/multipaz-doctypes-iosx64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-doctypes-iosx64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-doctypes-iosx64/0.96.1-pre.2.ef0c0b51/multipaz-doctypes-iosx64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-doctypes-iosx64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../multipaz-doctypes-jvm/0.96.1-pre.2.ef0c0b51/multipaz-doctypes-jvm-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-doctypes-jvm",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../multipaz-doctypes-jvm/0.96.1-pre.2.ef0c0b51/multipaz-doctypes-jvm-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-doctypes-jvm",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../multipaz-doctypes-jvm/0.96.1-pre.2.ef0c0b51/multipaz-doctypes-jvm-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-doctypes-jvm",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    }
  ]
}
