{
  "formatVersion": "1.1",
  "component": {
    "url": "../../multipaz-longfellow/0.96.1-pre.2.ef0c0b51/multipaz-longfellow-0.96.1-pre.2.ef0c0b51.module",
    "group": "org.multipaz",
    "module": "multipaz-longfellow",
    "version": "0.96.1-pre.2.ef0c0b51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.multipaz",
          "module": "multipaz",
          "version": {
            "requires": "0.96.1-pre.2.ef0c0b51"
          }
        }
      ],
      "files": [
        {
          "name": "multipaz-longfellow-iosSimulatorArm64Main-0.96.1-pre.2.ef0c0b51.klib",
          "url": "multipaz-longfellow-iossimulatorarm64-0.96.1-pre.2.ef0c0b51.klib",
          "size": 44763,
          "sha512": "7ce512c335e61da864b98d0ec6cb478fac254b722ca9859f5b29fc9e9b9973a2641173cbaf9c2f6e4ac8aafccc3408ed4cc5c2acb0be514adae5e554246c850f",
          "sha256": "fab6d8a32bdb6d8ae309cf4b3e418c212d0c22581b24b2488afaae51af7346ad",
          "sha1": "b4fb22b17e23f2eb57467733f7126ff0faf1af6c",
          "md5": "014fc777cad7bdaa3c5f49e1a66a3c55"
        },
        {
          "name": "multipaz-longfellow-iosSimulatorArm64Cinterop-LongfellowMain-0.96.1-pre.2.ef0c0b51.klib",
          "url": "multipaz-longfellow-iossimulatorarm64-0.96.1-pre.2.ef0c0b51-cinterop-Longfellow.klib",
          "size": 699437,
          "sha512": "ef6aa4f2e5a6f679621c1d4ce3904f808d0630223b283fe8a982732037d73ec0a5084a0061755f145956b49cbd4a990552ebc4071c66e125c8bda4a321ad1ada",
          "sha256": "434b89d46e967d006eeb4d83231b8f23d2db1f3a1e103d93e42c3126e146295e",
          "sha1": "5627aa95fa6d8ea420098736e2684bb7a1ebc3b8",
          "md5": "b43191f9f1e4e7d6cbf4656500cddbcd"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "multipaz-longfellow-iossimulatorarm64-0.96.1-pre.2.ef0c0b51-sources.jar",
          "url": "multipaz-longfellow-iossimulatorarm64-0.96.1-pre.2.ef0c0b51-sources.jar",
          "size": 9974,
          "sha512": "e6f92303fbf4571aed214b0a06c3ebb6d6a8fa7d44623dc2d237f17b978e25faf7e5e17088e117f5f52e6f34124d9d403a8676abaa7613c905e3c690ea2090c1",
          "sha256": "9ab7367b25b1f2b9b566e8268b513b12e82cb0a8aa9dd45fdb44a7234211b805",
          "sha1": "04f53a53d47d7c987ab3a97ac598dc909abe02dd",
          "md5": "5e3648004489d2315bff4bb990a28969"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.multipaz",
          "module": "multipaz",
          "version": {
            "requires": "0.96.1-pre.2.ef0c0b51"
          }
        }
      ],
      "files": [
        {
          "name": "multipaz-longfellow-iossimulatorarm64-0.96.1-pre.2.ef0c0b51-metadata.jar",
          "url": "multipaz-longfellow-iossimulatorarm64-0.96.1-pre.2.ef0c0b51-metadata.jar",
          "size": 18118,
          "sha512": "00efaedf42213d3c99ccf897a91392a0833cba4db749fd2e47984120cb7e48eae9f4825aa0bc88d3f24064db105c1e8e547796528a9255a344c3ac0da4e01227",
          "sha256": "1ed5fd205ced4d139f0ff8001f7a496f3eadda7762ce0a341d99b948ecd787c8",
          "sha1": "798d5e8a0fcc78030e68b5531fd638464708c058",
          "md5": "ce42b9822f8c120092fda554ac8c9616"
        }
      ]
    }
  ]
}
