{
  "formatVersion": "1.1",
  "component": {
    "url": "../../multipaz-doctypes/0.96.1-pre.2.ef0c0b51/multipaz-doctypes-0.96.1-pre.2.ef0c0b51.module",
    "group": "org.multipaz",
    "module": "multipaz-doctypes",
    "version": "0.96.1-pre.2.ef0c0b51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.multipaz",
          "module": "multipaz",
          "version": {
            "requires": "0.96.1-pre.2.ef0c0b51"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "multipaz-doctypes-jvm-0.96.1-pre.2.ef0c0b51.jar",
          "url": "multipaz-doctypes-jvm-0.96.1-pre.2.ef0c0b51.jar",
          "size": 110660,
          "sha512": "47a1bd0194d136f76d950a2b6e4faf12b95dda317fdc1f75cc64f893f1ca7635f75997915e78906f3a779b797bce31397b315520fad25ca0fb495574a19c4f8a",
          "sha256": "38656bf16c5a3e199e56169f8426568cfbd57238f662ffd3d71f219659c1685a",
          "sha1": "eb63019a1bf0d8dfb6d0a318b613cb1dcec0011d",
          "md5": "84b773e572a430ece3e59dde103af8b1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.multipaz",
          "module": "multipaz",
          "version": {
            "requires": "0.96.1-pre.2.ef0c0b51"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "multipaz-doctypes-jvm-0.96.1-pre.2.ef0c0b51.jar",
          "url": "multipaz-doctypes-jvm-0.96.1-pre.2.ef0c0b51.jar",
          "size": 110660,
          "sha512": "47a1bd0194d136f76d950a2b6e4faf12b95dda317fdc1f75cc64f893f1ca7635f75997915e78906f3a779b797bce31397b315520fad25ca0fb495574a19c4f8a",
          "sha256": "38656bf16c5a3e199e56169f8426568cfbd57238f662ffd3d71f219659c1685a",
          "sha1": "eb63019a1bf0d8dfb6d0a318b613cb1dcec0011d",
          "md5": "84b773e572a430ece3e59dde103af8b1"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "multipaz-doctypes-jvm-0.96.1-pre.2.ef0c0b51-sources.jar",
          "url": "multipaz-doctypes-jvm-0.96.1-pre.2.ef0c0b51-sources.jar",
          "size": 43068,
          "sha512": "bee4c72e30c13a106cc0be85c5e24746bf454a555e53f5bda7b37a4780b9ca3d4f143c06f82baca27cde86856f0853f29f0ef6b0107f5feba73a0c0d460d025e",
          "sha256": "3bc212df7356d4dcf55f1521727dd9bb9b7c03ba33cfe1023ba4cd0467468c0a",
          "sha1": "d93af0296d7d7b3c473cc9493831c3ef79bc1753",
          "md5": "5f75aae9397a9283dc00263aa526d4fd"
        }
      ]
    }
  ]
}
