{
  "formatVersion": "1.1",
  "component": {
    "url": "../../multipaz/0.96.1-pre.2.ef0c0b51/multipaz-0.96.1-pre.2.ef0c0b51.module",
    "group": "org.multipaz",
    "module": "multipaz",
    "version": "0.96.1-pre.2.ef0c0b51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "multipaz-jvm-0.96.1-pre.2.ef0c0b51.jar",
          "url": "multipaz-jvm-0.96.1-pre.2.ef0c0b51.jar",
          "size": 2984072,
          "sha512": "a1a5f0cf2138eb5e5b699d30e22a1800d2e837637cfcf8c11e574ea676605851b247de910010709487f5cc7f6d8f4ec55c15ee7fe84878141e991321b7c07e4d",
          "sha256": "101c3bc8e8509bdb12991d0acff28ec1c73f2d4134d0cdb45364b3c88f2ef74b",
          "sha1": "bf21bc8fa9e3dddc757eb607877044d5e5f73615",
          "md5": "818d5d7a9101b9e642e87ee16ee98f8e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-java",
          "version": {
            "requires": "2.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "multipaz-jvm-0.96.1-pre.2.ef0c0b51.jar",
          "url": "multipaz-jvm-0.96.1-pre.2.ef0c0b51.jar",
          "size": 2984072,
          "sha512": "a1a5f0cf2138eb5e5b699d30e22a1800d2e837637cfcf8c11e574ea676605851b247de910010709487f5cc7f6d8f4ec55c15ee7fe84878141e991321b7c07e4d",
          "sha256": "101c3bc8e8509bdb12991d0acff28ec1c73f2d4134d0cdb45364b3c88f2ef74b",
          "sha1": "bf21bc8fa9e3dddc757eb607877044d5e5f73615",
          "md5": "818d5d7a9101b9e642e87ee16ee98f8e"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "multipaz-jvm-0.96.1-pre.2.ef0c0b51-sources.jar",
          "url": "multipaz-jvm-0.96.1-pre.2.ef0c0b51-sources.jar",
          "size": 676346,
          "sha512": "dcccdc52a49cfcfa0ef243cf11fca1394462576227eae68f018ecc56e7a2d10273a01e7ad5d1046e9a4199be7d2c65a6dac6e9abab819e52b7a9f9813e8e4daf",
          "sha256": "3f18429642af8a86e5b2674d365cb83d4185f35e2def49332ec226cedc2605f8",
          "sha1": "4c453ba83e2811e02fa6104256611b1c523941d5",
          "md5": "c71d16725b7bb062d938508bc8b11431"
        }
      ]
    }
  ]
}
