{
  "formatVersion": "1.1",
  "component": {
    "url": "../../multipaz-longfellow/0.96.1/multipaz-longfellow-0.96.1.module",
    "group": "org.multipaz",
    "module": "multipaz-longfellow",
    "version": "0.96.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.multipaz",
          "module": "multipaz",
          "version": {
            "requires": "0.96.1"
          }
        }
      ],
      "files": [
        {
          "name": "multipaz-longfellow-iosArm64Main-0.96.1.klib",
          "url": "multipaz-longfellow-iosarm64-0.96.1.klib",
          "size": 44696,
          "sha512": "75b10578a79e918247f6c1bfe0e83e0533e3d8b6b601c066b8357905a8b612a50e8c8f1f876bb13de9882a947344c01ef3b97be1cb4b10e454543a692f9816c6",
          "sha256": "c22cf4a80702e01edb5b1c1a17b20626fd1ce175dddbd5ece45ab6976b3056a9",
          "sha1": "1d10a880d009a159dcd0187e8719234ad27c80ae",
          "md5": "baced70ed46a2948f8634416e31e8d8e"
        },
        {
          "name": "multipaz-longfellow-iosArm64Cinterop-LongfellowMain-0.96.1.klib",
          "url": "multipaz-longfellow-iosarm64-0.96.1-cinterop-Longfellow.klib",
          "size": 694360,
          "sha512": "0eaf33e49c6d3bafe9f466c999b491f4d1aada1abc21d8764017fa19fb1ac2941f0cd99a5505b99c60bceae9072293902b40e4aa12b611c6b98eb1187d23a489",
          "sha256": "a8a7f5d33df4b9cd3db2f31597bb39498d99f94889581e32f8bc5244156d9a05",
          "sha1": "192ef7d9c57707825d5cd9f200f5b5d36aea5754",
          "md5": "c12c9d98100ddf4f97e78e345ad15813"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "multipaz-longfellow-iosarm64-0.96.1-sources.jar",
          "url": "multipaz-longfellow-iosarm64-0.96.1-sources.jar",
          "size": 9974,
          "sha512": "e6f92303fbf4571aed214b0a06c3ebb6d6a8fa7d44623dc2d237f17b978e25faf7e5e17088e117f5f52e6f34124d9d403a8676abaa7613c905e3c690ea2090c1",
          "sha256": "9ab7367b25b1f2b9b566e8268b513b12e82cb0a8aa9dd45fdb44a7234211b805",
          "sha1": "04f53a53d47d7c987ab3a97ac598dc909abe02dd",
          "md5": "5e3648004489d2315bff4bb990a28969"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.multipaz",
          "module": "multipaz",
          "version": {
            "requires": "0.96.1"
          }
        }
      ],
      "files": [
        {
          "name": "multipaz-longfellow-iosarm64-0.96.1-metadata.jar",
          "url": "multipaz-longfellow-iosarm64-0.96.1-metadata.jar",
          "size": 18118,
          "sha512": "528050356ddf2639a31571db30d3709191d9dddc43363055c7f95fa5372981cf87009286960bd7f016a0d0ede14cd9350c934354b83047b6400cd6f065872f99",
          "sha256": "d5f05ff88bd3caf5ff0eba2284c28ed41334fbf76b3154b7e50168151d42cc8e",
          "sha1": "07ee9d17c69512d38e639335422e4a093a696f26",
          "md5": "d06bd618340a47e195a91fbd69029288"
        }
      ]
    }
  ]
}
