{
  "formatVersion": "1.1",
  "component": {
    "group": "org.multipaz",
    "module": "multipaz-compose",
    "version": "0.96.1-pre.2.ef0c0b51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.multipaz",
          "module": "multipaz",
          "version": {
            "requires": "0.96.1-pre.2.ef0c0b51"
          }
        },
        {
          "group": "org.multipaz",
          "module": "multipaz-dcapi",
          "version": {
            "requires": "0.96.1-pre.2.ef0c0b51"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose-core",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "multipaz-compose-metadata-0.96.1-pre.2.ef0c0b51.jar",
          "url": "multipaz-compose-0.96.1-pre.2.ef0c0b51.jar",
          "size": 43194,
          "sha512": "2337587996f9956773b98806f4e239ef7145b30bf009c406a58125390d60668ab2333e5077e22b531eb009a5545a53835bedba9f90a5d6dfb136bcd4b7b9aff8",
          "sha256": "38cff795dfa1512c2338e7bb2f7f82e56e1902c203fb42160054d39f47350e68",
          "sha1": "995c8bd78876fdbea4be0155daeb6abe0082c0e8",
          "md5": "cd4359d964c902aa885ee99b94ae5a85"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "multipaz-compose-kotlin-0.96.1-pre.2.ef0c0b51-sources.jar",
          "url": "multipaz-compose-0.96.1-pre.2.ef0c0b51-sources.jar",
          "size": 95966,
          "sha512": "fa18bae12976afd9e9816a0593afd7b6d55e870a124926a14cd906005498ff3ba3d06e37239621dd047fdfb7b0d806356027b4eb7251b4edda2f9b65e2baa892",
          "sha256": "d7d8784c04ca29900b5a576727fa8a20656efdbe7c86aeacc731d3d55edaeb13",
          "sha1": "37d7d4bd6797d61f05ba6df244330e538e5a7a38",
          "md5": "84b46b1d3b6284aacaa839c5f99d3b49"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../multipaz-compose-android/0.96.1-pre.2.ef0c0b51/multipaz-compose-android-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-compose-android",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../multipaz-compose-android/0.96.1-pre.2.ef0c0b51/multipaz-compose-android-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-compose-android",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../multipaz-compose-android/0.96.1-pre.2.ef0c0b51/multipaz-compose-android-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-compose-android",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-compose-iosarm64/0.96.1-pre.2.ef0c0b51/multipaz-compose-iosarm64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-compose-iosarm64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-compose-iosarm64/0.96.1-pre.2.ef0c0b51/multipaz-compose-iosarm64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-compose-iosarm64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-compose-iosarm64/0.96.1-pre.2.ef0c0b51/multipaz-compose-iosarm64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-compose-iosarm64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-compose-iosarm64/0.96.1-pre.2.ef0c0b51/multipaz-compose-iosarm64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-compose-iosarm64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-compose-iossimulatorarm64/0.96.1-pre.2.ef0c0b51/multipaz-compose-iossimulatorarm64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-compose-iossimulatorarm64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-compose-iossimulatorarm64/0.96.1-pre.2.ef0c0b51/multipaz-compose-iossimulatorarm64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-compose-iossimulatorarm64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-compose-iossimulatorarm64/0.96.1-pre.2.ef0c0b51/multipaz-compose-iossimulatorarm64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-compose-iossimulatorarm64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-compose-iossimulatorarm64/0.96.1-pre.2.ef0c0b51/multipaz-compose-iossimulatorarm64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-compose-iossimulatorarm64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-compose-iosx64/0.96.1-pre.2.ef0c0b51/multipaz-compose-iosx64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-compose-iosx64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-compose-iosx64/0.96.1-pre.2.ef0c0b51/multipaz-compose-iosx64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-compose-iosx64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-compose-iosx64/0.96.1-pre.2.ef0c0b51/multipaz-compose-iosx64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-compose-iosx64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../multipaz-compose-iosx64/0.96.1-pre.2.ef0c0b51/multipaz-compose-iosx64-0.96.1-pre.2.ef0c0b51.module",
        "group": "org.multipaz",
        "module": "multipaz-compose-iosx64",
        "version": "0.96.1-pre.2.ef0c0b51"
      }
    }
  ]
}
