{
  "formatVersion": "1.1",
  "component": {
    "url": "../../multipaz/0.96.1/multipaz-0.96.1.module",
    "group": "org.multipaz",
    "module": "multipaz",
    "version": "0.96.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "multipaz-iosX64Main-0.96.1.klib",
          "url": "multipaz-iosx64-0.96.1.klib",
          "size": 2765342,
          "sha512": "1a2384445af0d3a895098033bb4f74f0d395f923f2c7eb398023819646dc54259bca02d7f267427789f4872af6ab069d1a79e232a8901400b5ec3a34f2022a89",
          "sha256": "370cb749e0016134016ffef936992af477f4d4b15056a79e6a7caa9e3b4d26f1",
          "sha1": "1a56cc9dad26da45b55aeba6603823db8eae3e1f",
          "md5": "0eccf82fb99d03830015754010796ec3"
        },
        {
          "name": "multipaz-iosX64Cinterop-SwiftBridgeMain-0.96.1.klib",
          "url": "multipaz-iosx64-0.96.1-cinterop-SwiftBridge.klib",
          "size": 145865,
          "sha512": "7ad85f685354da4c7d5233c66ece1e664a01e2ce173b6f1dfcae3a0378c75b7147caa78d1b0649f28827a272f810dae7f8a47730f2da0e8e676e3536a50d332f",
          "sha256": "f43e5753733031fae29565ced5d73ce2a2a9e77c0a6f06550564176fc31b07c5",
          "sha1": "6001d450db884f06cdf6c2062dbdbc0e708a2969",
          "md5": "0cd94a712831999a995e2ac5b5c4cde0"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "multipaz-iosx64-0.96.1-sources.jar",
          "url": "multipaz-iosx64-0.96.1-sources.jar",
          "size": 686312,
          "sha512": "0649ccd655b63cf5762329a0c08f4bd227c61664cf6c7d2d95328af467bb62436297d49e5f9dd9be0222354510dd8657445ef507a5e63272312fa4a7ebab1031",
          "sha256": "1e04e25d3dc8d7c4f70d1a45d11d1e3aaf2b066962b57a25a562f9f1d839eb58",
          "sha1": "0f8c8a094e882b6e76529836870ffddc64334bf0",
          "md5": "c88ef222632c5db9479f0a0f1744a8cb"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "multipaz-iosx64-0.96.1-metadata.jar",
          "url": "multipaz-iosx64-0.96.1-metadata.jar",
          "size": 40129,
          "sha512": "68ac3d73a27b02d1a53919daaecb6dec4648eb9ae68f21800783d1a9cad31612d213801b613fd69e9b327077024d0dc345b4afa2a1377c6678da39bfba028cea",
          "sha256": "46bdd9c48a387ce2515f90cf3ab80cd32baf95a9fe4d88c74b20cac1c0e4abd3",
          "sha1": "706b4b66307c36e6f6636422965fe38e81e633db",
          "md5": "ff508b0e77aed2ba21803a5924231f68"
        }
      ]
    }
  ]
}
