{
  "formatVersion": "1.1",
  "component": {
    "url": "../../multipaz-doctypes/0.96.1/multipaz-doctypes-0.96.1.module",
    "group": "org.multipaz",
    "module": "multipaz-doctypes",
    "version": "0.96.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.multipaz",
          "module": "multipaz",
          "version": {
            "requires": "0.96.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "multipaz-doctypes-iosArm64Main-0.96.1.klib",
          "url": "multipaz-doctypes-iosarm64-0.96.1.klib",
          "size": 122173,
          "sha512": "07c6182c74f8beb889b707950dd3822af1e6b0a55be5aedc76cc5675a44e2d01dd7bf26b2488957fa5d8fa5852785fbbd04960d08ba99bcab2797f7fdc6df345",
          "sha256": "2dad8483be757821d3d32dddf4510c3f48ed07550938a366ba654fbf604db020",
          "sha1": "965a4f947339764b503dc81ea8b5e49ae78bf43d",
          "md5": "65fec5c28e7ca720d1fc91c8f7680eed"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "multipaz-doctypes-iosarm64-0.96.1-sources.jar",
          "url": "multipaz-doctypes-iosarm64-0.96.1-sources.jar",
          "size": 43068,
          "sha512": "bee4c72e30c13a106cc0be85c5e24746bf454a555e53f5bda7b37a4780b9ca3d4f143c06f82baca27cde86856f0853f29f0ef6b0107f5feba73a0c0d460d025e",
          "sha256": "3bc212df7356d4dcf55f1521727dd9bb9b7c03ba33cfe1023ba4cd0467468c0a",
          "sha1": "d93af0296d7d7b3c473cc9493831c3ef79bc1753",
          "md5": "5f75aae9397a9283dc00263aa526d4fd"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.multipaz",
          "module": "multipaz",
          "version": {
            "requires": "0.96.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "multipaz-doctypes-iosarm64-0.96.1-metadata.jar",
          "url": "multipaz-doctypes-iosarm64-0.96.1-metadata.jar",
          "size": 261,
          "sha512": "694bf771916b092e604c59ce1c246b1386051b1b82e97c46d660462e8e622ec248c90d7a077684a024ecab0db07219ec2d4404de64499bdfaf7fbe3538ab9bde",
          "sha256": "dfc38368f24908d201982f91bfb2864996fff108d9d3a2398a7938019caf9adb",
          "sha1": "391795423ec591189cc51a2fdf3e2652233b4312",
          "md5": "40440711c2f584415163ec1f14939133"
        }
      ]
    }
  ]
}
