{
  "formatVersion": "1.1",
  "component": {
    "url": "../../multipaz-longfellow/0.96.1/multipaz-longfellow-0.96.1.module",
    "group": "org.multipaz",
    "module": "multipaz-longfellow",
    "version": "0.96.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "multipaz-longfellow-jvm-0.96.1.jar",
          "url": "multipaz-longfellow-jvm-0.96.1.jar",
          "size": 5489299,
          "sha512": "a4a72cb39f42fd1fd59001ec1eb149f1ba67444ae7d237e757baecfb233acc2ce4b9d34fcd33b053927776bc07cbaf5288d9228fc5339f887f38c5f124eabb28",
          "sha256": "b3295bd87003c606dbd8e098b6aafd501f438bef807822945766d8e04bc254ac",
          "sha1": "bdd0056a52f75ba327573215947bdd9e6bd4bc05",
          "md5": "a9e03cd5fe992aae4ea4bf7db4f2b781"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.multipaz",
          "module": "multipaz",
          "version": {
            "requires": "0.96.1"
          }
        }
      ],
      "files": [
        {
          "name": "multipaz-longfellow-jvm-0.96.1.jar",
          "url": "multipaz-longfellow-jvm-0.96.1.jar",
          "size": 5489299,
          "sha512": "a4a72cb39f42fd1fd59001ec1eb149f1ba67444ae7d237e757baecfb233acc2ce4b9d34fcd33b053927776bc07cbaf5288d9228fc5339f887f38c5f124eabb28",
          "sha256": "b3295bd87003c606dbd8e098b6aafd501f438bef807822945766d8e04bc254ac",
          "sha1": "bdd0056a52f75ba327573215947bdd9e6bd4bc05",
          "md5": "a9e03cd5fe992aae4ea4bf7db4f2b781"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "multipaz-longfellow-jvm-0.96.1-sources.jar",
          "url": "multipaz-longfellow-jvm-0.96.1-sources.jar",
          "size": 10667,
          "sha512": "b7648e8b0f3416d9e4fa8a5f8bf6aa30b39992bd375c919cca23ec8027f66b5a4d3307de1e3d2d8eafda79adceef89206a5dbcbaf5efecbe45ab9446ab8ed04c",
          "sha256": "59e99d2ad987b3adb54f5cbcbc3c149120680db97bf55aabfa0dacc12a1476cf",
          "sha1": "07682603d3e641675d38ba9b19fc7c3e503964ee",
          "md5": "85d462e788b5ee82c0018c76609a4b44"
        }
      ]
    }
  ]
}
