{
  "formatVersion": "1.1",
  "component": {
    "group": "org.multipaz",
    "module": "multipaz-cbor-rpc",
    "version": "0.96.1-pre.2.ef0c0b51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "multipaz-cbor-rpc-0.96.1-pre.2.ef0c0b51.jar",
          "url": "multipaz-cbor-rpc-0.96.1-pre.2.ef0c0b51.jar",
          "size": 89389,
          "sha512": "59c87736d8a983831863ba3c00c2a1f9640fcc89ad9e85d15c38b3c333231595cca1cddada4285b5431fc82af85f8aa70d7cf10b9522f50f5cc60030fd2a1b6c",
          "sha256": "f0d451e8f776721062cac59b8d0a66f92e2eadc62e61402e8c0ddf1115eeb6b3",
          "sha1": "feb2336630d097b704747852284e3c0b865549d0",
          "md5": "87c1599dede93a41fbbd0c326e3d2a3c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "multipaz-cbor-rpc-0.96.1-pre.2.ef0c0b51.jar",
          "url": "multipaz-cbor-rpc-0.96.1-pre.2.ef0c0b51.jar",
          "size": 89389,
          "sha512": "59c87736d8a983831863ba3c00c2a1f9640fcc89ad9e85d15c38b3c333231595cca1cddada4285b5431fc82af85f8aa70d7cf10b9522f50f5cc60030fd2a1b6c",
          "sha256": "f0d451e8f776721062cac59b8d0a66f92e2eadc62e61402e8c0ddf1115eeb6b3",
          "sha1": "feb2336630d097b704747852284e3c0b865549d0",
          "md5": "87c1599dede93a41fbbd0c326e3d2a3c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "multipaz-cbor-rpc-0.96.1-pre.2.ef0c0b51-sources.jar",
          "url": "multipaz-cbor-rpc-0.96.1-pre.2.ef0c0b51-sources.jar",
          "size": 23296,
          "sha512": "8a2447e9a7aeeaf09f889ad7c304280529f1eb8cd7e119e92d5c9b8f688458945c61e30197a72e71b7b914858839973122645febda923c08832900ced9610d25",
          "sha256": "1b603f4a4d5d8dd7b69c4454cfb7573baf0e8dd1bd2ce886a5466d4b0fd89d3d",
          "sha1": "6418980b632481c6e9293f490c04dbf516fa40be",
          "md5": "c0bb65ead4c95768b4c131902e4d1263"
        }
      ]
    }
  ]
}
